# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

block_cipher = None

added_datas = [
    ('web_ui', 'web_ui'),
    ('system_prompts', 'system_prompts'),
    ('skills', 'skills'),
    ('assets', 'assets'),
    ('agent_workspace', 'agent_workspace'),
]

hidden_imports = [
    'uvicorn',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.lifespans',
    'uvicorn.lifespans.on',
    'fastapi',
    'fastapi.staticfiles',
    'fastapi.middleware.cors',
    'starlette',
    'starlette.staticfiles',
    'starlette.middleware',
    'starlette.middleware.cors',
    'pydantic',
    'langchain_core',
    'langchain_ollama',
    'langchain_openai',
    'coderai.tools.terminal_manager',
    'coderai.core.agent_runtime',
    'coderai.server.fastapi_app',
    'coderai.server.web_app',
    'coderai.codebase.codebase_index',
    'coderai.core.context_builder',
    'coderai.codebase.git_manager',
    'coderai.memory.memory_manager',
    'coderai.memory.memory_graph',
    'coderai.skills.skill_tracker',
    'coderai.skills.skill_router',
    'coderai.core.prompt_manager',
    'coderai.skills.skills_manager',
    'coderai.tools.sandbox_runner',
    'coderai.core.session_manager',
    'coderai.memory.vector_store',
    'coderai.tools.tools',
    'coderai.tools.tool_parser',
    'coderai.codebase.workspace_filter',
    'coderai.codebase.project_intelligence',
    'coderai.codebase.syntax_chunker',
    'coderai.utils.approval_policy',
    'coderai.memory.hindsight_manager',
    'sqlite3',
    'sqlite_vec',
    'winpty',
    'websockets',
    'requests',
    'urllib3',
]

excludes = [
    'torch',
    'torchvision',
    'torchaudio',
    'tensorflow',
    'tensorboard',
    'keras',
    'transformers',
    'cv2',
    'grpc',
    'scipy',
    'pandas',
    'matplotlib',
    'PIL',
    'IPython',
    'notebook',
    'jupyter',
    'sympy',
    'sklearn',
    'pytest',
    'tkinter',
    'pycountry',
    'openpyxl',
    'docx',
    # The app uses no Qt; anaconda transitively has both bindings installed,
    # which PyInstaller refuses to collect together. Exclude both.
    'PyQt5',
    'PyQt6',
    'PySide2',
    'PySide6',
]

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=added_datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CoderAI_Workspace',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
